export const VOLUNTEER_REQUEST = "VOLUNTEER_REQUEST";
export const VOLUNTEER_ERROR = "VOLUNTEER_ERROR";



// Post

export const POST_VOLUNTEER_SUCCESS = "POST_VOLUNTEER_SUCCESS";

// Get

export const GET_VOLUNTEER_SUCCESS = "GET_VOLUNTEER_SUCCESS";

// Edit

export const EDIT_VOLUNTEER = "EDIT_VOLUNTEER";

// Delete

export const DELETE_VOLUNTEER_SUCCESS = "DELETE_VOLUNTEER_SUCCESS";
